Issues/issue 35
malinclarsson/mandatory-project-agile1- pull request #50
Opened 2020-01-02 18:42 UTC by Flashkeys

popup on new game. adding style later

2020-01-02 20:19 UTC, malinmickelsson requested changes
All css ska vara styled components ;)

2020-01-03 11:58 UTC, AvvyT commented
Kolla först hur ser ut Home nu så att inte orsaka massa onödiga konflikter => https://github.com/malinclarsson/mandatory-project-agile1-/blob/unstable/frontend/src/Home.jsx
Samt Chatt strukturen.

2020-01-07 08:31 UTC, sawariz0r reviewed
Vi mixar css och styled-components i popups, hade kunnat skrivas som stylade komponenter  :)

2020-01-07 08:59 UTC, malinmickelsson approved these changes
Nice! 👍

2020-01-08 14:02 UTC, sawariz0r approved these changes

2020-01-08 14:02 UTC, merged